### ISSUE TITLE
Error: packing files: Total size of files should exceed 0, make sure to provide some content

### ISSUE THREAD

**Issue by cryptotester** [nftstorage/nftup#10]
On Linux (Fedora 36), using the latest AppImage (beta0 from April 8th) or even source code (yarn;yarn start with node LTS 16.x)

I try to drag 5 PNG files (images I'm using for NFTs), each 4-5MB each. I get always this error

Error: packing files: Total size of files should exceed 0, make sure to provide some content

![image](https://user-images.githubusercontent.com/49552918/176183614-388823c5-1b5e-4cf3-9174-7d09021eb092.png)

Even if I choose the folder and drag the folder. Same issue. I was already prompted for the API, even if I clear it and submit the api again, same issue.

**Comment by cryptotester** [comment]
For anyone landing here, I was suggested to click on the drag box intstead of dragging files on it. It works.

For devs: I recommend on linux at least, to change that, either replace the error message with "try to click here instead of dragging" or something like that. IT would for sure help users. THX

**Comment by elizabeth-griffiths** [comment]
Here is the latest information regarding NFT.Storage Classic, including NFTUp, and your data. 

As of 30 June 2024, no new uploads to the Classic product (including NFTUp) will be accepted but if you have used the products before your data is safe. Your data is safely stored and accessible via the NFT.Storage Gateway and in decentralized long-term storage in the Filecoin Network. However, over time, latency and availability may degrade.

Check out the new version of NFT.Storage. For the new version, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage. Note that you need to upload the data to IPFS separately, we recommend using Pinata or Lighthouse with our referral links to support NFT.Storage: 
https://nft.storage/blog/announcing-our-new-partnerships-with-pinata-and-lighthouse
