### ISSUE TITLE
Hang, files processed larger than source?

### ISSUE THREAD

**Issue by atarev-crypto** [nftstorage/nftup#14]
Attempted to upload a large (23GB) folder, files appear to be in place but GUI is hung showing "23.88GB of 23.85GB", you will notice that's more than the source size! Additionally, my nft.storage account portal shows a status "Pinning" and "Queueing" more than 12 hours later. Was directed by dchoi in Discord to open an issue.

**Comment by atarev-crypto** [comment]
24 hours later status is still the same, NFTUP GUI still shows same status, and nft.storage account shows "Pinning" and "Queueing".

**Comment by alanshaw** [comment]
Not sure how this issue got missed! Any chance you can share the root CID so we can look into it?

**Comment by atarev-crypto** [comment]
> 

bafybeic2fagxd7ddbcxiydxguslsipwkpxuz7pj3vyxzeml2woejps2loy , it STILL Shows "Pinning" in the nft.storage UI although all the data appears to be present.
