### ISSUE TITLE
Window doesn't tile in tiling window managers

### ISSUE THREAD

**Issue by tomodachi94** [nftstorage/nftup#16]
The NFTUp window should tile neatly with tiling window managers like i3. Here's what it looks like as of now:

![image](https://user-images.githubusercontent.com/68489118/218921788-e0736b6c-609a-46c4-8396-24b8bd698ded.png)

It should tile something like this:

![image](https://user-images.githubusercontent.com/68489118/218922247-3f8d12c5-0ccd-4d9e-9102-53f84bb580aa.png)

Also, some keyboard shortcuts would be nice, but that's a separate feature request :)

**Comment by elizabeth-griffiths** [comment]
Here is the latest information regarding NFT.Storage Classic, including NFTUp, and your data. As of 30 June 2024, no new uploads to the Classic product (including NFTUp) will be accepted but if you have used the products before your data is safe. Your data is safely stored and accessible via the NFT.Storage Gateway and in decentralized long-term storage in the Filecoin Network. However, over time, latency and availability may degrade.

Check out the new version of NFT.Storage. For the new version, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage. Note that you need to upload the data to IPFS separately, we recommend using Pinata or Lighthouse with our referral links to support NFT.Storage: 
https://nft.storage/blog/announcing-our-new-partnerships-with-pinata-and-lighthouse
