### ISSUE TITLE
Uploading 45MB of JSON - error "Storing files: Unexpected token < in JSON at position 0"

### ISSUE THREAD

**Issue by programador16T** [nftstorage/nftup#17]
Hi!

I am getting this error when I try to upload a folder with 200,000 JSON files that altogether weigh 57 MB, but when it finishes, it gives me the following error. I tried uploading fewer files with the same format (exactly 100) and those were uploaded successfully, but I need to have all 200,000 files in the same package. Could someone please give me a hand? Thank you very much! 

![Captura de pantalla de 2023-03-14 09-30-15](https://user-images.githubusercontent.com/127867633/225041995-034ea584-d8e8-4e7d-9591-55ed2dca2363.png)

**Comment by Miladsasani** [comment]
same issue ...

**Comment by ArdariaWorld** [comment]
Their webworker on cloudflare does not have enough capacity to handle your request. 
You can't upload that much to IPFS with NFT.storage.
You will have to store by chunks, and reference different baseURI in your NFT depending on the chunck.

From our experience, you can upload around 20,000 files maximum of standard ERC-721 metadata.

You will upload 10 chunks of 20,000 files, get 10 differents CIDs and from your smart contract you can conditionaly send the correct CID depending on the chunk you are.

It's hackish and will consume more gas to get the tokenURI so it could be a bad idea but it's at least a workaround for your case.

**Comment by elizabeth-griffiths** [comment]
Here is the latest information regarding NFT.Storage Classic, including NFTUp, and your data. 

As of 30 June 2024, no new uploads to the Classic product (including NFTUp) will be accepted but if you have used the products before your data is safe. Your data is safely stored and accessible via the NFT.Storage Gateway and in decentralized long-term storage in the Filecoin Network. However, over time, latency and availability may degrade.

Check out the new version of NFT.Storage. For the new version, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage. 

Note that you need to upload the data to IPFS separately, we recommend using Pinata or Lighthouse with our referral links to support NFT.Storage: 
https://nft.storage/blog/announcing-our-new-partnerships-with-pinata-and-lighthouse
