### ISSUE TITLE
Error: storing files: API Key is malformed or failed to parse.

### ISSUE THREAD

**Issue by headhunt3r** [nftstorage/nftup#22]
Hello , i'm trying to send files and every time i get the message Error: storing files: API Key is malformed or failed to parse. even with new keys appear this message.

**Comment by felipecalixtoreis** [comment]
Me too, the same problem and no solution until now.

**Comment by mortium91** [comment]
some problem

**Comment by cryptolukarg** [comment]
Tambien el mismo problema

**Comment by elizabeth-griffiths** [comment]
Hi All -
Here is the latest information regarding NFT.Storage Classic, including NFTUp, and your data. As of 30 June 2024, no new uploads to the Classic product (including NFTUp) will be accepted but if you have used the products before your data is safe. Your data is safely stored and accessible via the NFT.Storage Gateway and in decentralized long-term storage in the Filecoin Network. However, over time, latency and availability may degrade.

Check out the new version of NFT.Storage. For the new version, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage. Note that you need to upload the data to IPFS separately, we recommend using Pinata or Lighthouse with our referral links to support NFT.Storage: 
https://nft.storage/blog/announcing-our-new-partnerships-with-pinata-and-lighthouse
