### ISSUE TITLE
Uploading 16GB of images - error "Storing files: User not found"

### ISSUE THREAD

**Issue by sfnzr6** [nftstorage/nftup#4]
This is consistently happening for this large upload. It happens after getting between 20% and 80% of the upload complete... Anyone know what's happening?

![image](https://user-images.githubusercontent.com/102914902/162475631-d03abb45-1f4f-48ef-b05c-364af0da1a9e.png)

**Comment by alanshaw** [comment]
Did you delete the API key you're using? Try using `Tools > Clear API token` and get a new key and try again.

**Comment by Logosvahed** [comment]
Hi 
what is the problem that this error is given?what should i do to solve this error?
error: storing files:API Key is malformed or failed to parse.

**Comment by ironcap-crypto** [comment]
> Did you delete the API key you're using? Try using Tools > Clear API token and get a new key and try again.

Tried this yet it doesn't work, mine was aggregate of 13G of all files in the folder
