### ISSUE TITLE
Metadata example to point to the right image ipfs location

### ISSUE THREAD

**Issue by dohomi** [nftstorage/nftup#6]
Hello

You mention in your blog post :

`
You can upload any file structure you want. If you are doing something like a HashLips build, you can upload the assets and metadata at the same time by dragging them both to the upload box.
`

I am not sure how the metadata would upload the right image ipfs location on the upload? I uploaded images and metadata in the same go but the ipfs location wasn't updated.

**Comment by foufrix** [comment]
I'd also like a more in-depth example of one NFT with image and metadata to see how to upload it with NFT Up 🙏

**Comment by elizabeth-griffiths** [comment]
Here is the latest information regarding NFT.Storage Classic, including NFTUp, and your data. 

As of 30 June 2024, no new uploads to the Classic product (including NFTUp) will be accepted but if you have used the products before your data is safe. Your data is safely stored and accessible via the NFT.Storage Gateway and in decentralized long-term storage in the Filecoin Network. However, over time, latency and availability may degrade.

Check out the new version of NFT.Storage. For the new version, first mint your NFTs then send us the NFT data—metadata and imagery CIDs, blockchain(s) minted on, contract address and token IDs. We store these in long term Filecoin storage. Note that you need to upload the data to IPFS separately, we recommend using Pinata or Lighthouse with our referral links to support NFT.Storage: 
https://nft.storage/blog/announcing-our-new-partnerships-with-pinata-and-lighthouse
