### ISSUE TITLE
Error: storing files: API Key is malformed or failed to parse.

### ISSUE THREAD

**Issue by jimmy070593** [nftstorage/nftup#8]
Whenever I am uploading my nft folder on NFTUP its saying Error: storing files: API Key is malformed or failed to parse.
<img width="1080" alt="nftup" src="https://user-images.githubusercontent.com/99327007/174323914-3c987562-c7c0-43a6-95b9-90e22e3c6366.png">

**Comment by alanshaw** [comment]
Use tools > clear API token and copy/paste your API token again when prompted.
